import "@/styles/globals.css";
import type { FC } from "react";
type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Sample",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="ja">
      <body
      // className={`${InterFont.variable} ${DancingScriptFont.variable} ${NotoSansGeorgianFont.variable} ${LibreBaskervilleFont.variable} `}
      >
        {props.children}
      </body>
    </html>
  );
};

export default RootLayout;
