import {
  // DancingScriptFont,
  // InterFont,
  // LibreBaskervilleFont,
  // NotoSansGeorgianFont,
  NotoSerifJPFont,
  LoraFont,
} from "@/config/fonts";
import "@/styles/globals.css";
import type { FC } from "react";
type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Sample",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="ja">
      <body
        // className={`${InterFont.variable} ${DancingScriptFont.variable} ${NotoSansGeorgianFont.variable} ${LibreBaskervilleFont.variable} `}
        className={`${NotoSerifJPFont.variable} ${LoraFont.variable} `}
      >
        <main>{props.children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
